# Generated by Django 6.0.1 on 2026-01-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('troca', 'Troca de Óleo'), ('reparo', 'Reparo'), ('assistencia', 'Assistência'), ('vistoria', 'Vistoria'), ('manutencao', 'Manutenção Periódica')], max_length=20)),
                ('data_agendada', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendada'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('troca', 'Troca de Óleo'), ('reparo', 'Reparo'), ('assistencia', 'Assistência'), ('vistoria', 'Vistoria'), ('manutencao', 'Manutenção Periódica')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_manutencao', models.DateTimeField()),
                ('data_proxima', models.DateTimeField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_manutencao'],
            },
        ),
    ]
