# Generated by Django 6.0.1 on 2026-01-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_moto', models.CharField(max_length=100)),
                ('modelo_moto', models.CharField(max_length=100)),
                ('ano_moto', models.IntegerField()),
                ('nome_peca', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_original', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['marca_moto', 'modelo_moto', 'ano_moto'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
