# Generated by Django 6.0.1 on 2026-01-09 04:27

import motos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='ano',
            field=models.IntegerField(validators=[motos.models.validate_ano_moto]),
        ),
        migrations.AlterField(
            model_name='moto',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[motos.models.validate_placa]),
        ),
    ]
