# Generated by Django 6.0.1 on 2026-01-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_plan_fornecedor_subscription'),
        ('manutencoes', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-prioritario', 'data_agendada'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='prioritario',
            field=models.BooleanField(default=False, help_text='Agendamento prioritário (PRO)'),
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('destinatario', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio_programada', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio_real', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='manutencoes.agendamento')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['data_envio_programada'],
            },
        ),
        migrations.CreateModel(
            name='PontosFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_fidelidade', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pontos de Fidelidade',
                'verbose_name_plural': 'Pontos de Fidelidade',
            },
        ),
    ]
