# Generated by Django 6.0.1 on 2026-01-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0003_alter_agendamento_options_agendamento_prioritario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosfidelidade',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Lembrete',
        ),
        migrations.DeleteModel(
            name='PontosFidelidade',
        ),
    ]
