# Generated by Django 4.2.8 on 2026-01-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_duplicate_plan_fields'),
        ('manutencoes', '0004_remove_pontosfidelidade_cliente_delete_lembrete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_fidelidade', to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'Pontos de Fidelidade',
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('destinatario', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio_programada', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio_real', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='manutencoes.agendamento')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
            },
        ),
    ]
