# Generated by Django 6.0.1 on 2026-01-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0006_peca_itemagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='FotoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pecas/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='manutencoes.peca')),
            ],
            options={
                'verbose_name': 'Foto de Peça',
                'verbose_name_plural': 'Fotos de Peças',
                'ordering': ['data_criacao'],
                'unique_together': {('peca', 'imagem')},
            },
        ),
    ]
