# Generated by Django 6.0.1 on 2026-01-17 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0007_add_fotos_and_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_id', models.CharField(blank=True, help_text='ID de sessão para usuários não logados', max_length=255, null=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço no momento da adição ao carrinho', max_digits=10)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencoes.peca')),
                ('usuario', models.ForeignKey(blank=True, help_text='Null para carrinhos anônimos (localStorage)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
                'ordering': ['-data_adicao'],
                'unique_together': {('sessao_id', 'peca'), ('usuario', 'peca')},
            },
        ),
    ]
