# Generated by Django 6.0.1 on 2026-01-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0008_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto', max_length=255),
        ),
    ]
