# Generated by Django 6.0.1 on 2026-01-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0009_peca_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
