# Generated by Django 6.0.1 on 2026-01-09 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cpf_alter_cliente_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Básico'), ('pro', 'PRO')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_clientes', models.IntegerField(default=100)),
                ('max_motos', models.IntegerField(default=100)),
                ('max_agendamentos', models.IntegerField(default=100)),
                ('has_app_mobile', models.BooleanField(default=False)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('has_lembretes', models.BooleanField(default=False)),
                ('has_fornecedores', models.BooleanField(default=False)),
                ('has_chat_suporte', models.BooleanField(default=False)),
                ('has_backup_nuvem', models.BooleanField(default=False)),
                ('has_ia_diagnostico', models.BooleanField(default=False)),
                ('has_plano_fidelidade', models.BooleanField(default=False)),
                ('has_agendamentos_prioritarios', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente')], default='ativa', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_renovacao', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
