# Generated by Django 6.0.1 on 2026-01-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_plan_has_imagem_3d_plan_has_loja_plan_has_manuais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='has_imagem_3d',
        ),
        migrations.DeleteModel(
            name='Imagem3D',
        ),
    ]
