# Generated by Django 6.0.1 on 2026-01-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_fidelidade', to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'Pontos de Fidelidade',
            },
        ),
        migrations.DeleteModel(
            name='ManualsBase',
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='produtoloja',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Loja'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Site'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Assinaturas'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='has_manuais',
        ),
    ]
