# Generated by Django 4.2.8 on 2026-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_pontosfidelidade_delete_manualsbase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_agendamentos_prioritarios',
            field=models.BooleanField(default=False, help_text='Agendamentos com prioridade'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_app_mobile',
            field=models.BooleanField(default=False, help_text='Acesso via aplicativo móvel'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_backup_nuvem',
            field=models.BooleanField(default=False, help_text='Backup automático na nuvem'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_chat_suporte',
            field=models.BooleanField(default=False, help_text='Chat de suporte prioritário'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_fornecedores',
            field=models.BooleanField(default=False, help_text='Gerenciamento de fornecedores'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_ia_diagnostico',
            field=models.BooleanField(default=False, help_text='IA para diagnóstico de problemas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_lembretes',
            field=models.BooleanField(default=False, help_text='Sistema de lembretes automáticos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_plano_fidelidade',
            field=models.BooleanField(default=False, help_text='Sistema de fidelidade de clientes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_whatsapp',
            field=models.BooleanField(default=False, help_text='Integração com WhatsApp'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_agendamentos',
            field=models.IntegerField(default=100, help_text='Número máximo de agendamentos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_clientes',
            field=models.IntegerField(default=100, help_text='Número máximo de clientes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_motos',
            field=models.IntegerField(default=100, help_text='Número máximo de motos'),
        ),
        migrations.DeleteModel(
            name='PontosFidelidade',
        ),
    ]
