# Generated by Django 6.0.1 on 2026-01-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_duplicate_plan_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoloja',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Produto da Loja', 'verbose_name_plural': 'Produtos da Loja'},
        ),
    ]
