# Generated by Django 6.0.1 on 2026-01-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_produtoloja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='representante_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='representante_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
