# Generated by Django 6.0.1 on 2026-01-09 03:32

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[clientes.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[clientes.models.validate_telefone]),
        ),
    ]
