# Generated by Django 6.0.1 on 2026-01-09 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_plan_fornecedor_subscription'),
        ('motos', '0002_alter_moto_ano_alter_moto_placa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_imagem_3d',
            field=models.BooleanField(default=False, help_text='Imagens 3D dos modelos de motos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_loja',
            field=models.BooleanField(default=False, help_text='Loja para vender produtos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_manuais',
            field=models.BooleanField(default=False, help_text='Banco de dados com manuais de reparo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Gratuito'), ('pro', 'PRO'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Imagem3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_3d', models.FileField(help_text='Arquivo .obj, .gltf ou .glb', upload_to='modelos_3d/')),
                ('imagem_preview', models.ImageField(upload_to='imagens_3d_preview/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_3d', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Imagem 3D',
                'verbose_name_plural': 'Imagens 3D',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ManualsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('tipo_reparo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='manuais/')),
                ('url_externo', models.URLField(blank=True, null=True)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('tempo_estimado', models.CharField(help_text='Ex: 30 minutos', max_length=100)),
                ('ferramentas_necessarias', models.TextField(help_text='Lista de ferramentas necessárias')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Manual de Reparo',
                'verbose_name_plural': 'Manuais de Reparo',
                'ordering': ['-data_criacao'],
                'unique_together': {('marca', 'modelo', 'ano', 'tipo_reparo')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('categoria', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_loja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto da Loja',
                'verbose_name_plural': 'Produtos da Loja',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
