# Generated by Django 4.2.8 on 2026-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/thumbs/'),
        ),
    ]
